version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitoring_allinone
    # Gunakan network_mode: host agar Suricata bisa memonitor traffic di host
    network_mode: "host"
    volumes:
      - ./docker/php:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/streamlit:/opt/app
      - ./db:/db
      # Volume untuk persistensi log Suricata
      - ./suricata_logs:/var/log/suricata
    # Port mapping tidak lagi diperlukan dalam network_mode: host
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "8501:8501"
    privileged: true
    stdin_open: true
    tty: true